### PR TITLE
Support for sending USSD messages.

### PR DESCRIPTION
**Pull request by JelmerT**
This PR adds support for sending [Unstructured Supplementary Service Data messages](https://en.wikipedia.org/wiki/Unstructured_Supplementary_Service_Data). USSD messages can, for example, be used by prepaid plans to query the available balance (ex: #999# on T-mobile etc.). 

The example is also updated and adds a new option under `u`. USSD answers from the network usually come immediately, and are displayed in the same fashion as an SMS.

I implemented this to use with the still in alpha [Thingconnect](http://www.thingconnect.cc/) service that uses USSDs to send small amounts of data over GSM for IoT projects.

### CODE REVIEW

**Comment by JelmerT** [comment]
Also cleaned up some trailing spaces.

**Comment by JelmerT** [comment]
Travis passed, but it seems like it's still throwing some unrelated errors though.

**Comment by toddtreece** [comment]
@JelmerT this will probably need input from @ladyada about the content of the pull req, but could you pull the latest master so travis runs again with the latest changes.

**Comment by JelmerT** [comment]
Travis seems happy :ok_hand:

**Comment by toddtreece** [comment]
@JelmerT thanks for merging in upstream. that'll make it easier to review once we get a chance to look over the changes

**Comment by JelmerT** [comment]
@ladyada did you get a chance to look over this PR? If there's anything stopping it from being pulled, just let me know!

**Comment by ladyada** [comment]
just super busy this week! :)

**Comment by JelmerT** [comment]
Sorry for my pushy-ness, take your time! No rush on this one. ;)

**Comment by JelmerT** [comment]
Any progress on this PR?

**Comment by ladyada** [comment]
sorry for the huge delay - was added tonight! :)

**Pull request closed without merging**
